---
- name: Deploy NGINX on target node
  hosts: k3s_nodes
  become: true

  tasks:
    - name: Apply Deployment manifest
      ansible.builtin.shell: kubectl apply -f ../k3s_manifests/nginx_deployment.yaml

    - name: Apply Service manifest
      ansible.builtin.shell: kubectl apply -f ../k3s_manifests/nginx_service.yaml

    - name: Get list of pods
      ansible.builtin.shell: kubectl get pods
      register: pods_output

    - name: Show pods output
      ansible.builtin.debug:
        var: pods_output.stdout_lines

    - name: Get the service address and port
      ansible.builtin.shell: kubectl get svc nginx-service
      register: address_link

    - name: Show the address
      ansible.builtin.debug:
        var: address_link.stdout_lines