---
- name: deploy nginx on target node
  hosts: k3s_nodes
  become: true

  tasks:
    - name: Apply Deployment manifest
      command: kubectl apply -f k3s_manifests/nginx_deployment.yaml
      changed_when: false
      become: true

    - name: Apply Service manifest
      command: kubectl apply -f k3s_manifests/nginx_service.yaml
      changed_when: false
      become: true

    - name: Get list of pods
      command: kubectl get pods
      changed_when: false
      become: true
      register: pods_output

    - name: Show pods output
      debug:
        var: pods_output.stdout_lines

    - name: Get the service address and port
      command: kubectl get svc nginx-service
      changed_when: false
      become: true
      register: address_link

    - name: Show the address
      debug:
        var: address_link.stdout_lines