---
- name: Install K3s on target node
  hosts: k3s_nodes
  become: true

  tasks:
    - name: Update the system
      ansible.builtin.shell: apt update && apt upgrade -y
      changed_when: false

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - curl
          - wget
          - git
          - unzip
          - vim
          - gnupg
          - lsb-release
          - apt-transport-https
          - ca-certificates
          - software-properties-common
        state: present
        update_cache: yes

    - name: Download K3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s_install.sh
        mode: '0755'

    - name: Run K3s installer
      ansible.builtin.shell: /tmp/k3s_install.sh
      args:
        creates: /usr/local/bin/k3s

    - name: Check K3s service status
      ansible.builtin.command: systemctl status k3s
      register: k3s_status
      changed_when: false
      ignore_errors: true

    - name: Show K3s status output
      ansible.builtin.debug:
        var: k3s_status.stdout
